from __future__ import annotations

from enum import Enum
from enum import unique


@unique
class Goal(Enum):
    """Goal to create a matchable pattern."""

    layer = "layer"
    line = "line"
    block_1x1x3 = "1x1x3"
    block_1x2x2 = "1x2x2"
    block_1x2x3 = "1x2x3"
    block_2x2x2 = "2x2x2"
    block_2x2x3 = "2x2x3"
    two_blocks = "two-blocks"
    centers = "centers"
    corners = "corners"
    cross = "cross"
    edges = "edges"
    co = "co"
    co_face = "co-face"
    co_htr = "co-htr"
    cp_layer = "cp-layer"
    dr = "dr"
    eo = "eo"
    eo_face = "eo-face"
    eo_line = "eo+line"
    eo_floppy = "eo-floppy"
    eo_htr = "eo-htr"
    ep_layer = "ep-layer"
    face = "face"
    fake_htr = "fake-htr"
    f2l = "f2l"
    f2l_co = "f2l+co"
    f2l_cp = "f2l+cp"
    f2l_eo = "f2l+eo"
    f2l_ep = "f2l+ep"
    f2l_ep_co = "f2l+ep+co"
    f2l_eo_cp = "f2l+eo+cp"
    f2l_face = "f2l+face"
    floppy = "floppy"
    htr = "htr"
    htr_like = "htr-like"
    minus_slice = "minus-slice"
    none = "none"
    leave_slice = "leave-slice"
    solved = "solved"
    xo = "xo"
    xo_htr = "xo-htr"
    xp_face = "xp-face"
    x_cross = "x-cross"
    xx_cross = "xx-cross"
    xx_cross_adjacent = "xx-cross-adjacent"
    xx_cross_diagonal = "xx-cross-diagonal"
    xxx_cross = "xxx-cross"
