from __future__ import annotations

from enum import Enum
from enum import unique


@unique
class Variant(Enum):
    none = "none"
    # Face
    left = "left"
    right = "right"
    front = "front"
    back = "back"
    up = "up"
    down = "down"
    # Corners
    ubl = "ubl"
    ubr = "ubr"
    ufl = "ufl"
    ufr = "ufr"
    dbl = "dbl"
    dbr = "dbr"
    dfl = "dfl"
    dfr = "dfr"
    # Edges
    ul = "ul"
    ur = "ur"
    uf = "uf"
    ub = "ub"
    dl = "dl"
    dr = "dr"
    df = "df"
    db = "db"
    fl = "fl"
    fr = "fr"
    bl = "bl"
    br = "br"
    # Axis
    lr = "lr"
    fb = "fb"
    ud = "ud"
    # Face + corner
    up_bl = "up-bl"
    up_br = "up-br"
    up_fl = "up-fl"
    up_fr = "up-fr"
    down_bl = "down-bl"
    down_br = "down-br"
    down_fl = "down-fl"
    down_fr = "down-fr"
    left_ub = "left-ub"
    left_db = "left-db"
    left_uf = "left-uf"
    left_df = "left-df"
    right_ub = "right-ub"
    right_db = "right-db"
    right_uf = "right-uf"
    right_df = "right-df"
    front_ul = "front-ul"
    front_ur = "front-ur"
    front_dl = "front-dl"
    front_dr = "front-dr"
    back_ul = "back-ul"
    back_ur = "back-ur"
    back_dl = "back-dl"
    back_dr = "back-dr"
    # Face + opposite corners
    up_bl_fr = "up-bl+fr"
    up_br_fl = "up-br+fl"
    down_bl_fr = "down-bl+fr"
    down_br_fl = "down-br+fl"
    left_ub_df = "left-ub+df"
    left_db_uf = "left-db+uf"
    right_ub_df = "right-ub+df"
    right_db_uf = "right-db+uf"
    front_ul_dr = "front-ul+dr"
    front_ur_dl = "front-ur+dl"
    back_ul_dr = "back-ul+dr"
    back_ur_dl = "back-ur+dl"
    # Face + edge
    up_l = "up-l"
    up_r = "up-r"
    up_f = "up-f"
    up_b = "up-b"
    down_l = "down-l"
    down_r = "down-r"
    down_f = "down-f"
    down_b = "down-b"
    left_u = "left-u"
    left_d = "left-d"
    left_f = "left-f"
    left_b = "left-b"
    right_u = "right-u"
    right_d = "right-d"
    right_f = "right-f"
    right_b = "right-b"
    front_u = "front-u"
    front_d = "front-d"
    front_l = "front-l"
    front_r = "front-r"
    back_u = "back-u"
    back_d = "back-d"
    back_l = "back-l"
    back_r = "back-r"
