from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from spruce.autotagger.pattern import get_patterns
from spruce.configuration.enumeration import Goal
from spruce.configuration.enumeration import SearchSide
from spruce.configuration.enumeration import Status
from spruce.configuration.enumeration import Variant
from spruce.representation import get_permutation
from spruce.solver.bidirectional import BidirectionalAlgorithm
from spruce.solver.interface import PermutationSolver
from spruce.solver.interface import SearchSummary

if TYPE_CHECKING:
    from collections.abc import Set as AbstractSet

    from spruce.move.meta import MoveMeta
    from spruce.move.sequence import MoveSequence
    from spruce.types import MoveSymbol

LOGGER = logging.getLogger(__name__)


def solve_pattern(
    sequence: MoveSequence,
    *,
    move_meta: MoveMeta,
    generator: AbstractSet[MoveSymbol],
    goal: Goal = Goal.solved,
    variants: list[Variant] | None = None,
    max_search_depth: int = 10,
    max_solutions: int = 1,
    search_side: SearchSide = SearchSide.normal,
    goal_sequence: MoveSequence | None = None,
    max_time: float = 60.0,
) -> SearchSummary[MoveSequence]:
    """Solve a goal pattern.

    High-level functionality:

    1. Initialize:
        - Use the generator to get the action space, which is the set of all possible moves in a
        permutation. It expands the action space to include the actions that are generated by each
        symbol. I.e. if the symbol is "U", then the action space will include "U", "U2", and "U'".
        - Get the pattern for the step. This is the "colored" state to match. The pattern
        can be seen as a way to color the indices of the puzzle, and allows for solving steps
        such as orientations, permutations and, on a cube, CFOP steps such as cross and F2L.
        - Find the initial permutation by applying the sequence. If the goal sequence is provided,
        then apply the inverted goal sequence. This allows the solver to find the shortest path
        between two permutations (i.e. the matching permutation does not have to be the identity).

    2. Setup the bidirectional solver:
        - Use the actions and pattern to optimize which indexes to use, removing redundant
       actions, indexes that are bijections of each other or always remains solved.
       This reduces the sizes of the permutations and the search space.
       - Use optimal data types to store the pattern, reducing memory usage.
       - Optimize the move order based on the action space.

    3. Solve:
        - Use the solver to find the shortest sequence of moves that transforms the
        initial permutation into a permutation that matches the pattern. The solver explores the
        state space from both the initial permutation under the pattern and the goal pattern
        simultaneously, meeting in the middle.

    Args:
        sequence (MoveSequence): Sequence to scramble the puzzle.
        move_meta (MoveMeta): Meta information about moves.
        generator (AbstractSet[MoveSymbol]): Set of move symbols generating the actions at each
            step.
        goal (Goal | None, optional): Goal to solve. Defaults to Goal.Solved.
        max_search_depth (int, optional): Maximum search depth. Defaults to 10.
        max_solutions (int, optional): Maximum number of solutions. Defaults to 1.
        search_side (SearchSide, optional): Search strategy (normal, inverse, both).
            Defaults to SearchSide.normal.
        goal_sequence (MoveSequence | None, optional): Sequence to scramble the goal permutation.
        max_time (float, optional): Maximum time in seconds. Defaults to 60.0.

    Returns:
        SearchSummary: Summary of the search.
    """
    LOGGER.info("Solving with goal '%s' and strategy '%s'..", goal.name, search_side.value)
    LOGGER.debug("Sequence: %s", sequence)

    actions = move_meta.get_actions(generator=generator)
    pattern = get_patterns(puzzle=move_meta.puzzle).get(goal)
    assert pattern is not None

    if goal_sequence is not None:
        inverse_goal_permutation = get_permutation(
            sequence=goal_sequence,
            move_meta=move_meta,
            invert_after=True,
        )
    else:
        inverse_goal_permutation = None

    permutation = get_permutation(
        sequence=sequence,
        initial_permutation=inverse_goal_permutation,
        move_meta=move_meta,
    )

    if search_side is SearchSide.both:
        search_sides = [SearchSide.normal, SearchSide.inverse]
    else:
        search_sides = [search_side]

    if variants is not None and len(variants) > 0:
        if not all(variant in pattern.variants for variant in variants):
            raise ValueError(f"Got unknown variants {variants} for goal {goal}")
    else:
        variants = list(pattern.variants)

    all_solutions: list[MoveSequence] = []
    status = Status.failure
    total_walltime = 0.0
    validator_key = goal.value if pattern.validator is not None else None

    for variant in variants:
        solver = PermutationSolver.from_actions_and_pattern(
            algorithm=BidirectionalAlgorithm(),
            actions=actions,
            pattern=pattern[variant],
            validator_key=validator_key,
            optimize_indices=validator_key is None,
            debug=True,
        )

        for side in search_sides:
            remaining_time = max_time - total_walltime
            if remaining_time <= 0:
                break

            pattern_summary = solver.search(
                permutations=[permutation],
                max_solutions_per_permutation=max_solutions,
                max_search_depth=max_search_depth,
                max_time=remaining_time,
                side=side,
            )

            total_walltime += pattern_summary.walltime
            if pattern_summary.status is Status.failure:
                continue

            status = Status.success
            all_solutions.extend(solution.sequence for solution in pattern_summary.solutions)

    unique_solutions = {str(solution): solution for solution in all_solutions}
    solutions = sorted(
        unique_solutions.values(),
        key=lambda solution: (len(solution), str(solution)),
    )[:max_solutions]

    LOGGER.info(
        "Solver found %s solutions in %.3fs",
        len(solutions),
        total_walltime,
    )

    search_summary = SearchSummary(
        solutions=solutions,
        walltime=total_walltime,
        status=status,
    )

    return search_summary
